spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xhr_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cronaldo7
    driver-class-name: com.mysql.cj.jdbc.Driver